name: Configuration Update Manager
type: module
description: 'Adds an updates report and revert functionality to configuration management'
# core: 8.x
configure: config_update.report
dependencies:
  - config

# Information added by Drupal.org packaging script on 2015-07-01
version: '8.x-1.x-dev'
core: '8.x'
project: 'config_update'
datestamp: 1435759440
