module:
  admin_toolbar: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  dcz_article: 0
  dcz_custom_blocks: 0
  dcz_migrate: 0
  dcz_tags_taxonomy: 0
  dcz_user: 0
  devel_generate: 0
  editor: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  history: 0
  image: 0
  jssor: 0
  juicebox: 0
  language: 0
  layout_discovery: 0
  layout_plugin: 0
  libraries: 0
  link: 0
  locale: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  mollom: 0
  node: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  paragraphs: 0
  path: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  youtube: 0
  ds: 1
  forum: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  dcz: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  dcz_skin: 0
langcode: cs
profile: dcz
