session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    cs: cs
    '': null
  domains:
    en: ''
    cs: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: cs
