module:
  admin_toolbar: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  datetime: 0
  dblog: 0
  dcz_article: 0
  dcz_migrate: 0
  dcz_tags_taxonomy: 0
  dcz_user: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  history: 0
  image: 0
  link: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  forum: 1
  menu_link_content: 1
  views: 10
  dcz: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
