hotlink: false
origin: 'https://www.drupal.cz'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
_core:
  default_config_hash: CQLKbL2AgHGqE2ilC8yF4Mhg142d5_lgO6nJF7Ws66w
langcode: cs
